### ISSUE TITLE
CircleImageView ClassCastException

### ISSUE THREAD

**Issue by knkmsht** [tylersuehr7/chips-input-layout#10]
java.lang.ClassCastException: de.hdodenhof.circleimageview.CircleImageView cannot be cast to com.tylersuehr.chips.CircleImageView
                                                       at com.tylersuehr.chips.ChipView.<init>(ChipView.java:54)
                                                       at com.tylersuehr.chips.ChipView.<init>(ChipView.java:46)
                                                       at com.tylersuehr.chips.ChipView.newInstance(ChipView.java:330)
                                                       at com.tylersuehr.chips.ChipView.access$000(ChipView.java:25)
                                                       at com.tylersuehr.chips.ChipView$Builder.build(ChipView.java:325)
                                                       at com.tylersuehr.chips.ChipsInputLayout.getThemedChipView(ChipsInputLayout.java:651)
                                                       at com.tylersuehr.chips.ChipsAdapter.onCreateViewHolder(ChipsAdapter.java:55)
                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                       at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.fillWithLayouter(ChipsLayoutManager.java:858)
                                                       at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.fill(ChipsLayoutManager.java:821)
                                                       at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.onLayoutChildren(ChipsLayoutManager.java:719)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1680)
                                                       at android.support.v7.widget.RecyclerView.focusSearch(RecyclerView.java:2411)
                                                       at android.view.View.focusSearch(View.java:7346)
                                                       at android.widget.TextView.onCreateInputConnection(TextView.java:6013)
                                                       at com.tylersuehr.chips.ChipEditText.onCreateInputConnection(ChipEditText.java:43)
                                                       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1179)
                                                       at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1129)
                                                       at android.widget.TextView.setText(TextView.java:4003)
                                                       at android.widget.TextView.setText(TextView.java:3941)
                                                       at android.widget.EditText.setText(EditText.java:85)
                                                       at android.widget.TextView.setText(TextView.java:3916)
                                                       at com.tylersuehr.chips.ChipsInputLayout.onFilteredChipClick(ChipsInputLayout.java:100)
                                                       at com.tylersuehr.chips.FilterableChipsAdapter$Holder.onClick(FilterableChipsAdapter.java:142)
                                                       at android.view.View.performClick(View.java:4832)
                                                       at android.view.View$PerformClick.run(View.java:19844)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5319)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

I meet this when I click the FilterableChipList, this is awesome lib of complement the dynamic filter !

**Comment by gokrish6670** [comment]
me too facing

**Comment by knkmsht** [comment]
I seem to have solved, I upgraded the api platform to 26, restart android studio just fine.

**Comment by tylersuehr7** [comment]
I cannot seem to replicate this issue :( could any of y'nze guys list the steps taken to cause this?

**Comment by AnindyaPal** [comment]
Any one solved???
