### ISSUE TITLE
Crash when app:chip_showDetails is set to false and a chip is clicked

### ISSUE THREAD

**Issue by ihordzikovskyy** [tylersuehr7/chips-input-layout#24]
java.lang.NullPointerException: Attempt to invoke interface method 'void com.tylersuehr.chips.ChipView$OnChipClickListener.onChipClicked(com.tylersuehr.chips.ChipView)' on a null object reference
                                                                 at com.tylersuehr.chips.ChipView$1.onClick(ChipView.java:107)
                                                                 at android.view.View.performClick(View.java:6256)
                                                                 at android.view.View$PerformClick.run(View.java:24701)
                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by tylersuehr7** [comment]
Thanks posting info about this issue! I've put a fix for this bug in release 2.3
